# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:


# This is the minimum version number required.
# Update this, if you use features of a newer version
#  fastlane_version "2.38.1"

default_platform :ios

platform :ios do
  def set_testflight_build_number(build_number)
    return increment_build_number({
      build_number: build_number
    })
  end

  def increment_testflight_build_number
    build_number = latest_testflight_build_number() + 1
    return set_testflight_build_number(build_number)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :internal do

    # make sure everything clean
    cocoapods
    build_number = increment_testflight_build_number
    # Build and upload
    gym(scheme: "samplepro",
        workspace: "samplepro.xcworkspace",
        configuration: "Release",
        include_bitcode: true) # Build your app - more options available
    pilot(ipa: "./samplepro.xcworkspace.ipa", skip_waiting_for_build_processing: true)
  end

  desc "Sync Certificates"
  lane :certs do
    match(readonly: true, type: "development")
    match(readonly: true, type: "appstore")
  end

  desc "Generate Certificates"
  lane :gen_certs do
    match(readonly: false, type: "development")
    match(readonly: false, type: "appstore")
  end
  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
